resource_group_name    = "vm_terraform_rg"
location               = "West Europe"
virtual_network_name   = "vnetprod"
subnet_name            = "subnetprod"
public_ip_name         = "publicipprod"
network_interface_name = "nicprod"
windows_vm_name        = "windows10"