resource_group_name    = "kv_terraform_rg"
location               = "West Europe"
keyvault_name          = "demokv01090"
secret_name            = "DatabasePassword"
secret_value           = "@Aa123456789!"