resource_group_name     = "rg-terraform-web-sql-db"
resource_group_location = "northeurope"
app_service_plan_name   = "appserviceplan-web"
app_service_name        = "terraform-web-019"
sql_server_name         = "terraform-sqlserver-019"
sql_database_name       = "ProductsDB"
sql_admin_login         = "user01"
sql_admin_password      = "@Aa123456789!"
